version: '3'

services:
  whoami:
    image: traefik/whoami:v1.10
    hostname: '{{.Node.Hostname}}'
    networks:
      - ConexxoHubNet
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.rule=Host(`www3.persev.info`)
        - traefik.http.routers.whoami.entrypoints=websecure
        - traefik.http.routers.whoami.priority=1
        - traefik.http.routers.whoami.tls.certresolver=letsencryptresolver
        - traefik.http.services.whoami.loadbalancer.server.port=80

networks:
  ConexxoHubNet:
    external: true

