## Criando a stack anythingllm.yaml
cat > anythingllm${1:+_$1}.yaml <<EOL
version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  anythingllm${1:+_$1}:
    image: mintplexlabs/anythingllm:latest

    volumes:
      - anythingllm${1:+_$1}_storage:/app/server/storage
      - anythingllm${1:+_$1}_hotdir:/app/collector/hotdir
      - anythingllm${1:+_$1}_outputs:/app/collector/outputs

    networks:
      - $nome_rede_interna ## Nome da rede interna

    environment:
      - SERVER_PORT=3001
      - STORAGE_DIR=/app/server/storage
      - UID=1000
      - GID=1000

      ## Dados Qdrant
      - VECTOR_DB=qdrant
      - QDRANT_ENDPOINT=$qdrant_anythingllm
      - QDRANT_API_KEY=$api_qdrant_anythingllm

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.anythingllm${1:+_$1}.rule=Host(\`$url_anythingllm\`)
        - traefik.http.services.anythingllm${1:+_$1}.loadbalancer.server.port=3001
        - traefik.http.routers.anythingllm${1:+_$1}.service=anythingllm${1:+_$1}
        - traefik.http.routers.anythingllm${1:+_$1}.tls.certresolver=letsencryptresolver
        - traefik.http.routers.anythingllm${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.anythingllm${1:+_$1}.tls=true

## --------------------------- ORION --------------------------- ##

volumes:
  anythingllm${1:+_$1}_storage:
    external: true
    name: anythingllm${1:+_$1}_storage
  anythingllm${1:+_$1}_hotdir:
    external: true
    name: anythingllm${1:+_$1}_hotdir
  anythingllm${1:+_$1}_outputs:
    external: true
    name: anythingllm${1:+_$1}_outputs

networks:
  $nome_rede_interna: ## Nome da rede interna
    name: $nome_rede_interna ## Nome da rede interna
    external: true
EOL
if [ $? -eq 0 ]; then
    echo "1/10 - [ OK ] - Criando Stack"
else
    echo "1/10 - [ OFF ] - Criando Stack"
    echo "Não foi possivel criar a stack do anythingllm"
fi