## Criando a stack baserow.yaml
cat > baserow${1:+_$1}.yaml <<EOL
version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  baserow${1:+_$1}:
    image: baserow/baserow:latest ## Versão do Baserow

    volumes:
      - baserow${1:+_$1}_data:/baserow/data

    networks:
      - $nome_rede_interna ## Nome da rede interna

    environment:
      ## Url do baserow
      - BASEROW_PUBLIC_URL=https://$url_baserow

      ## Porta do baserow
      - BASEROW_CADDY_ADDRESSES=:80

      ## Dados SMTP
      - EMAIL_SMTP=true ## Ativar/Desativar SMTP
      - FROM_EMAIL=$mail_baserow ## Email
      - EMAIL_SMTP_USER=$user_baserow ## Email (ou usuario)
      - EMAIL_SMTP_PASSWORD=$pass_baserow ## Senha do SMTP
      - EMAIL_SMTP_HOST=$host_baserow ## Host SMTP
      - EMAIL_SMTP_PORT=$porta_baserow ## Porta SMTP
      $ssl_baserow_environments

      ## Dados Redis
      - REDIS_URL=redis://redis:6379/11

      ## Dados postgres:
      - DATABASE_URL=postgresql://postgres:$senha_postgres@postgres:5432/baserow${1:+_$1}

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      #resources:
      #  limits:
      #    cpus: "1"
      #    memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.baserow${1:+_$1}.rule=Host(\`$url_baserow\`)
        - traefik.http.services.baserow${1:+_$1}.loadbalancer.server.port=80
        - traefik.http.routers.baserow${1:+_$1}.service=baserow${1:+_$1}
        - traefik.http.routers.baserow${1:+_$1}.tls.certresolver=letsencryptresolver
        - traefik.http.routers.baserow${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.baserow${1:+_$1}.tls=true

## --------------------------- ORION --------------------------- ##

volumes:
  baserow${1:+_$1}_data:
    external: true
    name: baserow${1:+_$1}_data

networks:
  $nome_rede_interna: ## Nome da rede interna
    name: $nome_rede_interna ## Nome da rede interna
    external: true

EOL