## Criando a stack clickhouse.yaml
cat > clickhouse${1:+_$1}.yaml <<EOL
version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  clickhouse:${1:+_$1}
    image: clickhouse/clickhouse-server:23.8.8.20-alpine

    volumes:
      - clickhouse${1:+_$1}_data:/var/lib/clickhouse
      - clickhouse${1:+_$1}_log:/var/log/clickhouse-server

    networks:
      - $nome_rede_interna ## Nome da rede interna
    #ports:
    #  - "8123:8123"
    #  - "9000:9000"
    #  - "9009:9009"

    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=$user_clickhouse
      - CLICKHOUSE_PASSWORD=$pass_clickhouse

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.clickhouse${1:+_$1}.rule=Host(\`$url_clickhouse\`)
        - traefik.http.services.clickhouse${1:+_$1}.loadbalancer.server.port=8123
        - traefik.http.routers.clickhouse${1:+_$1}.service=clickhouse${1:+_$1}
        - traefik.http.routers.clickhouse${1:+_$1}.tls.certresolver=letsencryptresolver
        - traefik.http.services.clickhouse${1:+_$1}.loadbalancer.passHostHeader=true
        - traefik.http.routers.clickhouse${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.clickhouse${1:+_$1}.tls=true        

## --------------------------- ORION --------------------------- ##

volumes:
  clickhouse${1:+_$1}_data:
    external: true
    name: clickhouse${1:+_$1}_data
  clickhouse${1:+_$1}_log:
    external: true
    name: clickhouse${1:+_$1}_log
  
networks:
  $nome_rede_interna:
    external: true
    name: $nome_rede_interna
EOL