version: "3.7"
services:
  directus}:
    image: directus/directus:latest

    volumes:
      - directus_uploads:/directus/uploads
      - directus_data:/directus/database

    networks:
      - {{network_name}}

    environment:
      ## Dados de acesso
      - ADMIN_EMAIL={{directus_email}}
      - ADMIN_PASSWORD={{directus_password}}
      - PUBLIC_URL=https://{{directus_url}}

      ## Dados SMTP
      - EMAIL_SMTP_USER={{directus_smtp_email}}
      - EMAIL_SMTP_PASSWORD={{directus_smtp_password}}
      - EMAIL_SMTP_HOST={{directus_smtp_host}}
      - EMAIL_SMTP_PORT={{directus_smtp_port}}
      - EMAIL_SMTP_SECURE={{directus_smtp_secure}}

      ## Minio
      - STORAGE_s3_KEY={{s3_access_key}}
      - STORAGE_s3_SECRET={{s3_secret_key}}
      - STORAGE_s3_BUCKET=directus
      - STORAGE_s3_REGION=eu-south
      - STORAGE_s3_ENDPOINT=$url_s3

      ## Redis
      - REDIS=redis://redis:6379/4

      ## Secret Keys & Env
      - KEY=$key_directus
      - SECRET=$key_directus2
      - APP_ENV=production

      ## Dados Postgres
      - DB_CLIENT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=directus${1:+_$1}
      - DB_USER=postgres
      - DB_PASSWORD=$senha_postgres
      - DB_CONNECTION_STRING=postgresql://postgres:$senha_postgres@postgres:5432/directus${1:+_$1}
      - DB_PREFIX=drcts_

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.directus${1:+_$1}.rule=Host(\`$url_directus\`)
        - traefik.http.services.directus${1:+_$1}.loadbalancer.server.port=8055
        - traefik.http.routers.directus${1:+_$1}.service=directus${1:+_$1}
        - traefik.http.routers.directus${1:+_$1}.tls.certresolver=letsencryptresolver
        - traefik.http.routers.directus${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.directus${1:+_$1}.tls=true

## --------------------------- ORION --------------------------- ##

volumes:
  directus${1:+_$1}_uploads:
    external: true
    name: directus${1:+_$1}_uploads
  directus${1:+_$1}_data:
    external: true
    name: directus${1:+_$1}_data

networks:
  $nome_rede_interna:
    external: true
    attachable: true
    name: $nome_rede_interna
EOL