version: "3.8"
services:
  firecrawl_api:
    image: oriondesign/firecrawl-api:latest
    command: [ "pnpm", "run", "start:production" ]

    networks:
     - {{network_name}}

    environment:
      ## Credencial
      - FIRECRAWL_API_KEY={{firecrawl_api_key}}

      ## Dados do Redis
      - REDIS_URL=redis://redis:6379
      - REDIS_RATE_LIMIT_URL=redis://redis:6379
      
      ## Dados da OpenAI
      - OPENAI_API_KEY={{firecrawl_openai_api_key}}
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - MODEL_NAME=gpt-4o
      
      # Dados do ScrapingBee
      - SCRAPING_BEE_API_KEY=
      - HOST=0.0.0.0
      
      # Dados do Webhook e Debug
      - SELF_HOSTED_WEBHOOK_URL=
      - LOGGING_LEVEL=DEBUG

      ## Dados do Supabase
      - USE_DB_AUTHENTICATION=false
      #- SUPABASE_URL=
      #- SUPABASE_ANON_TOKEN=
      #- SUPABASE_SERVICE_TOKEN=

      ## Outras configurações
      - PORT=3002
      - NUM_WORKERS_PER_QUEUE=8 
      - FLY_PROCESS_GROUP=app
      - PLAYWRIGHT_MICROSERVICE_URL=http://firecrawl_playwright:3000

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.firecrawl_api.rule=Host(\`{{firecrawl_url}}\`)
        - traefik.http.services.firecrawl_api.loadbalancer.server.port=3002
        - traefik.http.routers.firecrawl_api.service=firecrawl_api
        - traefik.http.routers.firecrawl_api.tls.certresolver=letsencryptresolver
        - traefik.http.routers.firecrawl_api.entrypoints=websecure
        - traefik.http.routers.firecrawl_api.tls=true

  firecrawl_worker:
    image: oriondesign/firecrawl-api:latest
    command: [ "pnpm", "run", "workers" ]

    networks:
      - {{network_name}}

    environment:
      ## Credentials
      - FIRECRAWL_API_KEY={{firecrawl_api_key}}
      
      ## Redis
      - REDIS_URL=redis://redis:6379
      - REDIS_RATE_LIMIT_URL=redis://redis:6379
      
      ## OpenAI
      - OPENAI_API_KEY={{firecrawl_openai_api_key}}
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - MODEL_NAME=gpt-4o
      
      # ScrapingBee
      - SCRAPING_BEE_API_KEY=
      - HOST=0.0.0.0
      
      # Webhook e Debug
      - SELF_HOSTED_WEBHOOK_URL=
      - LOGGING_LEVEL=DEBUG

      ## Supabase
      - USE_DB_AUTHENTICATION=false
      #- SUPABASE_URL=
      #- SUPABASE_ANON_TOKEN=
      #- SUPABASE_SERVICE_TOKEN=

      ## Settings
      - PORT=3002
      - NUM_WORKERS_PER_QUEUE=8 
      - FLY_PROCESS_GROUP=worker
      - PLAYWRIGHT_MICROSERVICE_URL=http://firecrawl_playwright:3000

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  firecrawl_playwright:
    image: oriondesign/firecrawl-playwright-service:latest

    networks:
      - {{network_name}}

    environment:
      - PORT=3000
      - PROXY_SERVER=http://proxy-server.com:3128
      - PROXY_USERNAME=admin
      - PROXY_PASSWORD=admin
      - BLOCK_MEDIA=true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
