## Criando a stack flowise.yaml
cat > flowise${1:+_$1}.yaml <<EOL
version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  flowise${1:+_$1}:
    image: flowiseai/flowise:latest ## Versão do Flowise

    volumes:
     - flowise${1:+_$1}_data:/root/.flowise

    networks:
     - $nome_rede_interna ## Nome da rede interna

    environment:
     ## Dados de acesso
     - FLOWISE_USERNAME=$user_flowise
     - FLOWISE_PASSWORD=$pass_flowise

     ## Dados do Postgres
     - DATABASE_TYPE=postgres
     - DATABASE_HOST=postgres
     - DATABASE_PORT=5432
     - DATABASE_USER=postgres
     - DATABASE_PASSWORD=$senha_postgres
     - DATABASE_NAME=flowise${1:+_$1}

     ## Encryption Key
     - FLOWISE_SECRETKEY_OVERWRITE=$encryption_key

     ## Diretório das API Keys
     - APIKEY_PATH=/root/.flowise
     - SECRETKEY_PATH=/root/.flowise

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.flowise${1:+_$1}.rule=Host(\`$url_flowise\`) ## Url da aplicação
        - traefik.http.services.flowise${1:+_$1}.loadBalancer.server.port=3000
        - traefik.http.routers.flowise${1:+_$1}.service=flowise${1:+_$1}
        - traefik.http.routers.flowise${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.flowise${1:+_$1}.tls.certresolver=letsencryptresolver

## --------------------------- ORION --------------------------- ##

volumes:
  flowise${1:+_$1}_data:
    external: true

networks:
  $nome_rede_interna: ## Nome da rede interna
    external: true
    name: $nome_rede_interna ## Nome da rede interna
EOL