version: "3.7"
services:

  formbricks:
    image: formbricks/formbricks:latest

    volumes:
      - formbricks_data:/home/nextjs/apps/web/uploads/

    networks:
      - {{network_name}}

    environment:
      ## Url da aplicação
      - WEBAPP_URL=https://{{formbricks_url}}
      - NEXTAUTH_URL=https://{{formbricks_url}}

      ## Banco de dados Postgres
      - DATABASE_URL=postgresql://postgres:{{pgvector_password}}@pgvector:5432/formbricks?schema=public

      ## Licença Enterprise ou Self-hosting
      ## Request self-hosting license: https://oriondesign.art.br/formbricks_licence/
      - ENTERPRISE_LICENSE_KEY=

      ## Random keys 32 characters
      - ENCRYPTION_KEY={{formbricks_encryption_key}}
      - NEXTAUTH_SECRET={{formbricks_next_key}}
      - CRON_SECRET={{formbricks_cron_key}}

      ## SMTP
      - MAIL_FROM={{formbricks_email}}
      - SMTP_HOST={{formbricks_host}}
      - SMTP_PORT={{formbricks_port}}
      - SMTP_SECURE_ENABLED={{formbricks_ssl}}
      - SMTP_USER={{formbricks_smtp_username}}
      - SMTP_PASSWORD={{formbricks_smtp_password}}

      ## Ativar/Desativar registros e convites (0= false | 1= true)
      - SIGNUP_DISABLED=0
      - INVITE_DISABLED=0
      - EMAIL_VERIFICATION_DISABLED=0
      - PASSWORD_RESET_DISABLED=0

      ## Dados do Formbricks (para pesquisa)
      - NEXT_PUBLIC_FORMBRICKS_API_HOST=
      - NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID=
      - NEXT_PUBLIC_FORMBRICKS_ONBOARDING_SURVEY_ID=

      ## Login Google Cloud
      - GOOGLE_AUTH_ENABLED=0
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=

      ## Google Sheets
      - GOOGLE_SHEETS_CLIENT_ID=
      - GOOGLE_SHEETS_CLIENT_SECRET=
      - GOOGLE_SHEETS_REDIRECT_URL=

      ## Login Github
      - GITHUB_AUTH_ENABLED=0
      - GITHUB_ID=
      - GITHUB_SECRET=

      ## Login Github
      - NOTION_OAUTH_CLIENT_ID=
      - NOTION_OAUTH_CLIENT_SECRET=   
      
      ## Login Airtable
      - AIRTABLE_CLIENT_ID=

      ## Termos e politica de privacidade
      #- PRIVACY_URL=
      #- TERMS_URL=
      #- IMPRINT_URL=

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.formbricks.rule=Host(\`{{formbricks_url}}\`)
        - traefik.http.services.formbricks.loadbalancer.server.port=3000
        - traefik.http.routers.formbricks.service=formbricks
        - traefik.http.routers.formbricks.tls.certresolver=letsencryptresolver
        - traefik.http.routers.formbricks.entrypoints=websecure
        - traefik.http.routers.formbricks.tls=true

volumes:
  formbricks_data:
    external: true
    name: formbricks_data

networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
