version: "3.7"
services:
  glpi:
    image: diouxx/glpi:latest

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - glpi_glpi:/var/www/html/glpi

    networks:
      - {{network_name}}

    environment:
      - TIMEZONE=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.glpi.rule=Host(\`{{url_glpi}}\`)
        - traefik.http.routers.glpi.service=glpi
        - traefik.http.routers.glpi.tls.certresolver=letsencryptresolver
        - traefik.http.routers.glpi.entrypoints=websecure
        - traefik.http.routers.glpi.tls=true
        - traefik.http.services.glpi.loadbalancer.server.port=80

volumes:
  glpi_glpi:
    external: true
    name: glpi_glpi

networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
