## Criando a stack krayincrm.yaml
cat > krayincrm${1:+_$1}.yaml <<EOL
version: "3.7"
services:

  ## --------------------------- ORION --------------------------- ##

  krayin${1:+_$1}:
    image: webkul/krayin:2.0.4

    volumes:
      - krayin${1:+_$1}_data:/var/www/html/laravel-crm

    networks:
      - $nome_rede_interna ## Nome da rede interna
      
    environment:
      ## Dados de acesso
      - krayin_PUBLIC_URL=https://$url_krayincrm
      - APP_URL=https://$url_krayincrm
      - krayin_CADDY_ADDRESSES=:80
      - APP_ENV=production
      - APP_KEY=$secret_key
      - APP_DEBUG=false
      - APP_TIMEZONE=America/Sao_Paulo
      - APP_LOCALE=pt_BR
      - APP_CURRENCY=BRL
      - SANCTUM_STATEFUL_DOMAINS=https://$url_krayincrm/public

      ## Configuração do Banco de Dados
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=krayin${1:+_$1}
      - DB_USERNAME=root
      - DB_PASSWORD=$senha_mysql
      - DB_PREFIX=

      ## Configurações de e-mail
      - MAIL_MAILER=smtp
      - MAIL_FROM_ADDRESS=$email_krayincrm ## mude
      - MAIL_USERNAME=$usuario_email_krayincrm ## mude
      - MAIL_PASSWORD=$senha_email_krayincrm ## mude
      - MAIL_HOST=$smtp_email_krayincrm ## mude
      - MAIL_PORT=$porta_smtp_krayincrm ## mude
      - MAIL_ENCRYPTION=$smtp_secure_krayincrm
      - MAIL_FROM_NAME="OrionCRM" ## mude

      ## Configurações de Cache e Sessão
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120

      ## Configurações de Redis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.krayin${1:+_$1}.rule=Host(\`$url_krayincrm\`) && PathPrefix(\`/\`) ## Url do Krayin
        - traefik.http.services.krayin${1:+_$1}.loadbalancer.server.port=80
        - traefik.http.routers.krayin${1:+_$1}.service=krayin${1:+_$1}
        - traefik.http.routers.krayin${1:+_$1}.tls.certresolver=letsencryptresolver
        - traefik.http.routers.krayin${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.krayin${1:+_$1}.tls=true

## --------------------------- ORION --------------------------- ##

volumes:
  krayin${1:+_$1}_data:
    external: true
    name: krayin${1:+_$1}_data

networks:
  $nome_rede_interna: ## Nome da rede interna
    name: $nome_rede_interna ## Nome da rede interna
    external: true
EOL