## Criando a stack mattermost.yaml
cat > mattermost${1:+_$1}.yaml <<EOL
version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  mattermost${1:+_$1}:
    image: mattermost/mattermost-team-edition:latest

    volumes:
      - mattermost${1:+_$1}_data:/mattermost/data
      - mattermost${1:+_$1}_config:/mattermost/config
      - mattermost${1:+_$1}_logs:/mattermost/logs
      - mattermost${1:+_$1}_plugins:/mattermost/plugins
      - mattermost${1:+_$1}_client_plugins:/mattermost/client/plugins

    networks:
      - $nome_rede_interna

    environment:
      ## Dados de acesso
      - MM_SERVICESETTINGS_SITEURL=https://$url_mattermost

      ## Dados do Postgres
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://postgres:$senha_postgres@postgres:5432/mattermost${1:+_$1}?sslmode=disable&connect_timeout=10

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.mattermost${1:+_$1}.rule=Host(\`$url_mattermost\`)
        - traefik.http.routers.mattermost${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.mattermost${1:+_$1}.tls.certresolver=letsencryptresolver
        - traefik.http.routers.mattermost${1:+_$1}.service=mattermost${1:+_$1}
        - traefik.http.services.mattermost${1:+_$1}.loadbalancer.server.port=8065
        - traefik.http.services.mattermost${1:+_$1}.loadbalancer.passhostheader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.mattermost${1:+_$1}.middlewares=sslheader@docker

## --------------------------- ORION --------------------------- ##

volumes:
  mattermost${1:+_$1}_data:
    external: true
    name: mattermost${1:+_$1}_data
  mattermost${1:+_$1}_config:
    external: true
    name: mattermost${1:+_$1}_config
  mattermost${1:+_$1}_logs:
    external: true
    name: mattermost${1:+_$1}_logs
  mattermost${1:+_$1}_plugins:
    external: true
    name: mattermost${1:+_$1}_plugins
  mattermost${1:+_$1}_client_plugins:
    external: true
    name: mattermost${1:+_$1}_client_plugins

networks:
  $nome_rede_interna:
    external: true
    name: $nome_rede_interna
EOL