## Criando a stack mautic.yaml
cat > mautic${1:+_$1}.yaml <<EOL
version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  mautic_web${1:+_$1}:
    image: mautic/mautic:latest ## Versão do Mautic

    volumes:
      - mautic${1:+_$1}_config:/var/www/html/config
      - mautic${1:+_$1}_docroot:/var/www/html/docroot
      - mautic${1:+_$1}_media:/var/www/html/docroot/media
      - mautic${1:+_$1}_logs:/var/www/html/var/logs
      - mautic${1:+_$1}_cron:/opt/mautic/cron

    networks:
      - $nome_rede_interna ## Nome da rede interna

    environment:
      ## Dados MySQL
      - MAUTIC_DB_NAME=mautic${1:+_$1}
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=$senha_mysql
      
      ## Dados de acesso
      - MAUTIC_ADMIN_EMAIL=$email_mautic
      - MAUTIC_ADMIN_USERNAME=$user_mautic
      - MAUTIC_ADMIN_PASSWORD=$senha_email_mautic
      - MAUTIC_URL=https://$url_mautic

      ## Configurações
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]
      - DOCKER_MAUTIC_ROLE=mautic_web
      - DOCKER_MAUTIC_WORKERS_CONSUME_EMAIL=2
      - DOCKER_MAUTIC_WORKERS_CONSUME_HIT=2
      - DOCKER_MAUTIC_WORKERS_CONSUME_FAILED=2

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.mautic${1:+_$1}.rule=Host(\`$url_mautic\`) # substitua SeuDominio.com.br pelo seu domínio
        - traefik.http.services.mautic${1:+_$1}.loadbalancer.server.port=80
        - traefik.http.routers.mautic${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.mautic${1:+_$1}.service=mautic${1:+_$1}
        - traefik.http.routers.mautic${1:+_$1}.tls.certresolver=letsencryptresolver
        - traefik.http.services.mautic${1:+_$1}.loadbalancer.passHostHeader=true

## --------------------------- ORION --------------------------- ##

  mautic_worker${1:+_$1}:
    image: mautic/mautic:latest ## Versão do Mautic

    volumes:
      - mautic${1:+_$1}_config:/var/www/html/config
      - mautic${1:+_$1}_docroot:/var/www/html/docroot
      - mautic${1:+_$1}_media:/var/www/html/docroot/media
      - mautic${1:+_$1}_logs:/var/www/html/var/logs
      - mautic${1:+_$1}_cron:/opt/mautic/cron

    networks:
      - $nome_rede_interna ## Nome da rede interna

    environment:
      ## Dados MySQL
      - MAUTIC_DB_NAME=mautic${1:+_$1}
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=$senha_mysql
      
      ## Dados de acesso
      - MAUTIC_ADMIN_EMAIL=$email_mautic
      - MAUTIC_ADMIN_USERNAME=$user_mautic
      - MAUTIC_ADMIN_PASSWORD=$senha_email_mautic
      - MAUTIC_URL=https://$url_mautic

      ## Configurações
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]
      - DOCKER_MAUTIC_ROLE=mautic_worker
      - DOCKER_MAUTIC_WORKERS_CONSUME_EMAIL=2
      - DOCKER_MAUTIC_WORKERS_CONSUME_HIT=2
      - DOCKER_MAUTIC_WORKERS_CONSUME_FAILED=2

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M

## --------------------------- ORION --------------------------- ##

  mautic_cron${1:+_$1}:
    image: mautic/mautic:latest ## Versão do Mautic

    volumes:
      - mautic${1:+_$1}_config:/var/www/html/config
      - mautic${1:+_$1}_docroot:/var/www/html/docroot
      - mautic${1:+_$1}_media:/var/www/html/docroot/media
      - mautic${1:+_$1}_logs:/var/www/html/var/logs
      - mautic${1:+_$1}_cron:/opt/mautic/cron

    networks:
      - $nome_rede_interna ## Nome da rede interna

    environment:
      ## Dados MySQL
      - MAUTIC_DB_NAME=mautic${1:+_$1}
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=$senha_mysql
      
      ## Dados de acesso
      - MAUTIC_ADMIN_EMAIL=$email_mautic
      - MAUTIC_ADMIN_USERNAME=$user_mautic
      - MAUTIC_ADMIN_PASSWORD=$senha_email_mautic
      - MAUTIC_URL=https://$url_mautic

      ## Configurações
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]
      - DOCKER_MAUTIC_ROLE=mautic_cron
      - DOCKER_MAUTIC_WORKERS_CONSUME_EMAIL=2
      - DOCKER_MAUTIC_WORKERS_CONSUME_HIT=2
      - DOCKER_MAUTIC_WORKERS_CONSUME_FAILED=2

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

## --------------------------- ORION --------------------------- ##

volumes:
  mautic${1:+_$1}_config:
    external: true
    name: mautic${1:+_$1}_config
  mautic${1:+_$1}_docroot:
    external: true
    name: mautic${1:+_$1}_docroot
  mautic${1:+_$1}_media:
    external: true
    name: mautic${1:+_$1}_media
  mautic${1:+_$1}_logs:
    external: true
    name: mautic${1:+_$1}_logs
  mautic${1:+_$1}_cron:
    external: true
    name: mautic${1:+_$1}_cron

networks:
  $nome_rede_interna: ## Nome da rede interna
    name: $nome_rede_interna ## Nome da rede interna
    external: true
EOL