version: "3.7"
services:  
  pgadmin:
    image: dpage/pgadmin4:latest

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    networks:
      - {{network_name}}

    environment:
      ## Dados de Acesso
      - PGADMIN_DEFAULT_EMAIL={{pgadmin_username}}
      - PGADMIN_DEFAULT_PASSWORD={{pgadmin_password}}

    deploy:
      mode: replicated
      replicas: 1
      placement:
          constraints:
            - node.role == manager
      resources:
          limits:
            cpus: '0.4'
            memory: 256M
      labels:
          - traefik.enable=true
          - traefik.http.routers.pgadmin${1:+_$1}.rule=Host(\`{{pgadmin_url}}\`) ## Url da Ferramenta
          - traefik.http.services.pgadmin${1:+_$1}.loadbalancer.server.port=80
          - traefik.http.routers.pgadmin${1:+_$1}.service=pgadmin
          - traefik.http.routers.pgadmin${1:+_$1}.tls.certresolver=letsencryptresolver
          - traefik.http.routers.pgadmin${1:+_$1}.entrypoints=websecure
          - traefik.http.routers.pgadmin${1:+_$1}.tls=true

volumes:
  pgadmin_data:
    external: true
    
networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
EOL