## Criando a stack tooljet.yaml
cat > tooljet${1:+_$1}.yaml <<EOL
version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  tooljet${1:+_$1}_app:
    image: tooljet/tooljet:ee-lts-latest
    command: npm run start:prod

    networks:
      - $nome_rede_interna ## Nome da rede interna

    environment:
      ## Configuração básica
      - TOOLJET_HOST=https://$url_tooljet
      - SERVE_CLIENT=true
      - PORT=80

      ## Desativar novas inscrições
      - DISABLE_SIGNUPS=false

      ## Ativar perguntas no Onboarding
      - ENABLE_ONBOARDING_QUESTIONS_FOR_ALL_SIGN_UPS=true

      ## Chaves de segurança
      - LOCKBOX_MASTER_KEY=$master_key
      - SECRET_KEY_BASE=$secret_key

      ## Configuração do banco de dados principal
      - DATABASE_URL=postgres://postgres:$senha_postgres@postgres:5432/tooljet${1:+_$1}_app?sslmode=disable

      ## Configuração do banco interno do ToolJet
      - ENABLE_TOOLJET_DB=true
      - TOOLJET_DB=tooljet${1:+_$1}
      - TOOLJET_DB_USER=postgres
      - TOOLJET_DB_HOST=postgres
      - TOOLJET_DB_PASS=$senha_postgres

      ## Configuração do PostgREST
      - PGRST_HOST=tooljet_postgrest${1:+_$1}
      - PGRST_JWT_SECRET=$jwt_key

      ## Configuração do Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      ## Configuração do SMTP
      - DEFAULT_FROM_EMAIL=$email_smtp_tooljet
      - SMTP_USERNAME=$usuario_smtp_tooljet
      - SMTP_PASSWORD=$senha_smtp_tooljet
      - SMTP_DOMAIN=$host_smtp_tooljet
      - SMTP_PORT=$porta_smtp_tooljet

      ## Features do ToolJet
      - COMMENT_FEATURE_ENABLE=true
      - ENABLE_MULTIPLAYER_EDITING=true
      - ENABLE_MARKETPLACE_FEATURE=true

      ## Atualizações e expiração de sessão
      - CHECK_FOR_UPDATES=false
      - USER_SESSION_EXPIRY=120

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.tooljet${1:+_$1}.rule=Host(\`$url_tooljet\`)
        - traefik.http.services.tooljet${1:+_$1}.loadbalancer.server.port=80
        - traefik.http.routers.tooljet${1:+_$1}.service=tooljet${1:+_$1}
        - traefik.http.routers.tooljet${1:+_$1}.tls.certresolver=letsencryptresolver
        - traefik.http.routers.tooljet${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.tooljet${1:+_$1}.tls=true

  ## --------------------------- ToolJet PostgREST --------------------------- ##

  tooljet${1:+_$1}_postgrest:
    image: postgrest/postgrest:v12.0.2

    networks:
      - $nome_rede_interna ## Nome da rede interna

    environment:
      - PGRST_SERVER_PORT=80
      - PGRST_DB_URI=postgres://postgres:$senha_postgres@postgres:5432/tooljet${1:+_$1}_app?sslmode=disable
      - PGRST_DB_SCHEMA=public 
      - PGRST_DB_ANON_ROLE=anon 
      - PGRST_JWT_SECRET=$jwt_key
      - PGRST_JWT_AUD=tooljet${1:+_$1}

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- ORION --------------------------- ##

networks:
  $nome_rede_interna: ## Nome da rede interna
    name: $nome_rede_interna ## Nome da rede interna
    external: true
EOL