## Criando a stack traccar.yaml
cat > traccar${1:+_$1}.yaml <<EOL
version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  traccar${1:+_$1}:
    image: traccar/traccar:latest
    
    volumes:
      - /opt/traccar/logs:/opt/traccar${1:+_$1}/logs:rw
      - /opt/traccar/traccar.xml:/opt/traccar${1:+_$1}/conf/traccar.xml:ro
      - traccar${1:+_$1}_data:/opt/traccar/

    networks:
     - $nome_rede_interna ## Nome da rede interna

    environment:
     - JAVA_OPTS=-Xms1g -Xmx1g -Djava.net.preferIPv4Stack=true
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.traccar${1:+_$1}.rule=Host(\`$url_traccar\`)
        - traefik.http.services.traccar${1:+_$1}.loadbalancer.server.port=8082
        - traefik.http.routers.traccar${1:+_$1}.service=traccar${1:+_$1}
        - traefik.http.routers.traccar${1:+_$1}.tls.certresolver=letsencryptresolver
        - traefik.http.routers.traccar${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.traccar${1:+_$1}.tls=true

## --------------------------- ORION --------------------------- ##

  traccar${1:+_$1}_db:
    image: mysql:8.0

    volumes:
      - traccar${1:+_$1}_db:/var/lib/mysql

    networks:
     - $nome_rede_interna ## Nome da rede interna

    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=traccar
      - MYSQL_USER=traccar
      - MYSQL_PASSWORD=$gerar_senha_mysql

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- ORION --------------------------- ##

volumes:
  traccar${1:+_$1}_data:
    external: true
    name: traccar${1:+_$1}_data
  traccar${1:+_$1}_db:
    external: true
    name: traccar${1:+_$1}_db
    
networks:
  $nome_rede_interna: ## Nome da rede interna
    name: $nome_rede_interna ## Nome da rede interna
    external: true
EOL