## Criando a stack transcrevezap.yaml
cat > transcrevezap${1:+_$1}.yaml <<EOL

version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  transcrevezap${1:+_$1}:
    image: impacteai/transcrevezap:latest
    command: ./start.sh

    networks:
      - $nome_rede_interna

    environment:
      ## Configurações de acesso
      - MANAGER_USER=$user_transcrevezap
      - MANAGER_PASSWORD=$pass_transcrevezap

      ## Configurações Globais
      - API_DOMAIN=$api_transcrevezap
      - UVICORN_PORT=8005
      - UVICORN_HOST=0.0.0.0
      - UVICORN_RELOAD=true
      - UVICORN_WORKERS=1

      ## Configurações do Redis
      - REDIS_HOST=redis_transcrevezap${1:+_$1}
      - REDIS_PORT=6380

      ## Configurações de Debug
      - DEBUG_MODE=false
      - LOG_LEVEL=INFO

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.transcrevezap${1:+_$1}.rule=Host(\`$api_transcrevezap\`) ## url do transcrevezap
        - traefik.http.routers.transcrevezap${1:+_$1}.entrypoints=websecure
        - traefik.http.routers.transcrevezap${1:+_$1}.tls.certresolver=letsencryptresolver
        - traefik.http.services.transcrevezap${1:+_$1}.loadbalancer.server.port=8005
        - traefik.http.services.transcrevezap${1:+_$1}.loadbalancer.passHostHeader=true
        - traefik.http.routers.transcrevezap${1:+_$1}.service=transcrevezap${1:+_$1}
        - traefik.http.middlewares.traefik-compress.compress=true
        - traefik.http.routers.transcrevezap${1:+_$1}.middlewares=traefik-compress
        - traefik.http.routers.transcrevezap${1:+_$1}_manager.rule=Host(\`$url_transcrevezap\`) ## url do manager do transcrevezap
        - traefik.http.routers.transcrevezap${1:+_$1}_manager.entrypoints=websecure
        - traefik.http.routers.transcrevezap${1:+_$1}_manager.tls.certresolver=letsencryptresolver
        - traefik.http.services.transcrevezap${1:+_$1}_manager.loadbalancer.server.port=8501
        - traefik.http.routers.transcrevezap${1:+_$1}_manager.service=transcrevezap${1:+_$1}_manager

## --------------------------- ORION --------------------------- ##

  redis_transcrevezap${1:+_$1}:
    image: redis:6
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6380"
      ]

    volumes:
      - redis_transcrevezap${1:+_$1}_data:/data

    networks:
      - $nome_rede_interna

## --------------------------- ORION --------------------------- ##

volumes:
  redis_transcrevezap${1:+_$1}_data:
    external: true
    name: redis_transcrevezap${1:+_$1}_data

networks:
  $nome_rede_interna:
    external: true
    name: $nome_rede_interna
EOL