version: "3.7"
services:
  wuzapi:
    image: ruben18salazar/wuzapi:api
  
    volumes:
      - wuzapi_dbdata:/app/dbdata
      - wuzapi_files:/app/files
  
    networks:
      - {{network_name}}
  
    environment:
      ## Credencial
      - WUZAPI_ADMIN_TOKEN={{wuzapi_apikey}}
      - SECRET_KEY={{wuzapi_secretkey}}
  
      ## Postgres
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD={{postgres_password}}
      - DB_NAME=wuzapi
      - DB_PORT=5432
      - DB_DRIVER=postgres
  
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.role == manager
        resources:
          limits:
            cpus: "1"
            memory: 1024M
        labels:
          - traefik.enable=true
          - traefik.http.routers.wuzapi.rule=Host(\`{{wuzapi_url}}\`)
          - traefik.http.services.wuzapi.loadbalancer.server.port=8080
          - traefik.http.routers.wuzapi.service=wuzapi
          - traefik.http.routers.wuzapi.tls.certresolver=letsencryptresolver
          - traefik.http.routers.wuzapi.entrypoints=websecure
          - traefik.http.routers.wuzapi.tls=true

volumes:
  wuzapi_dbdata:
    external: true
    name: wuzapi_dbdata
  wuzapi_files:
    external: true
    name: wuzapi_files

networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
