version: "3.7"
services:
  appsmith:
    image: appsmith/appsmith-ee:latest

    volumes:
      - appsmith_data:/appsmith-stacks

    networks:
      - {{network_name}}

    environment:
      ## Appsmith Url
      - APPSMITH_CUSTOM_DOMAIN=https://{{appsmith_url}}

      ## Enable/unable signup
      - APPSMITH_SIGNUP_DISABLED=false

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.appsmith.rule=Host(\`{{appsmith_url}}\`)
        - traefik.http.routers.appsmith.entrypoints=websecure
        - traefik.http.routers.appsmith.tls.certresolver=letsencryptresolver
        - traefik.http.routers.appsmith.service=appsmith
        - traefik.http.services.appsmith.loadbalancer.server.port=80
        - traefik.http.services.appsmith.loadbalancer.passHostHeader=true

volumes:
  appsmith_data:
    external: true
    name: appsmith_data

networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
