version: "3.7"
services:
  directus:
    image: directus/directus:latest

    volumes:
      - directus_uploads:/directus/uploads
      - directus_data:/directus/database

    networks:
      - {{network_name}}

    environment:
      ## Dados de acesso
      - ADMIN_EMAIL={{directus_email}}
      - ADMIN_PASSWORD={{directus_password}}
      - PUBLIC_URL=https://{{directus_url}}

      ## Dados SMTP
      - EMAIL_SMTP_USER={{directus_smtp_email}}
      - EMAIL_SMTP_PASSWORD={{directus_smtp_password}}
      - EMAIL_SMTP_HOST={{directus_smtp_host}}
      - EMAIL_SMTP_PORT={{directus_smtp_port}}
      - EMAIL_SMTP_SECURE={{directus_smtp_secure}}

      ## Minio
      - STORAGE_s3_KEY={{s3_access_key}}
      - STORAGE_s3_SECRET={{s3_secret_key}}
      - STORAGE_s3_BUCKET=directus
      - STORAGE_s3_REGION=eu-south
<<<<<<< HEAD:stacks/directus.yaml
      - STORAGE_s3_ENDPOINT={{s3_url}}
=======
      - STORAGE_s3_ENDPOINT={{s2_url}}
>>>>>>> main:sandbox/stacks/directus.yaml

      ## Redis
      - REDIS=redis://redis:6379/4

      ## Secret Keys & Env
      - KEY={{directus_key}}
      - SECRET={{directus_secret}}
      - APP_ENV=production

      ## Dados Postgres
      - DB_CLIENT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=directus
      - DB_USER=postgres
      - DB_PASSWORD={{postgres_password}}
      - DB_CONNECTION_STRING=postgresql://postgres:{{postgres_password}}@postgres:5432/directus
      - DB_PREFIX=drcts_

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.directus.rule=Host(\`{{directus_url}}\`)
        - traefik.http.services.directus.loadbalancer.server.port=8055
        - traefik.http.routers.directus.service=directus
        - traefik.http.routers.directus.tls.certresolver=letsencryptresolver
        - traefik.http.routers.directus.entrypoints=websecure
        - traefik.http.routers.directus.tls=true

volumes:
  directus_uploads:
    external: true
    name: directus_uploads
  directus_data:
    external: true
    name: directus_data

networks:
  {{network_name}}:
    external: true
    attachable: true
    name: {{network_name}}
