version: "3.7"
services:

  docuseal:
    image: docuseal/docuseal:latest

    volumes:
      - docuseal_data:/data

    networks:
      - {{network_name}}

    environment:
      ## URLs
      - HOST={{docuseal_url}}
      - FORCE_SSL=true

      ## Secret Key
      - SECRET_KEY_BASE={{docuseal_key}}

      ## Dados do Postgres
      - DATABASE_URL=postgresql://postgres:{{postgres_password}}@postgres:5432/docuseal

      ## Dados SMTP
      - SMTP_USERNAME={{docuseal_smtp_username}}
      - SMTP_PASSWORD={{docuseal_smtp_password}}
      - SMTP_ADDRESS={{docuseal_smtp_host}}
      - SMTP_PORT={{docuseal_smtp_port}}
      - SMTP_FROM={{docuseal_smtp_from}}
      - SMTP_DOMAIN={{docuseal_smtp_host}}
      - SMTP_AUTHENTICATION=login

      ## Dados do S3
      ##- AWS_ACCESS_KEY_ID=
      ##- AWS_SECRET_ACCESS_KEY=
      ##- S3_ATTACHMENTS_BUCKET=
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.docuseal.rule=Host(`{{docuseal_url}}`)
        - traefik.http.services.docuseal.loadbalancer.server.port=3000
        - traefik.http.routers.docuseal.service=docuseal
        - traefik.http.routers.docuseal.tls.certresolver=letsencryptresolver
        - traefik.http.routers.docuseal.entrypoints=websecure
        - traefik.http.routers.docuseal.tls=true

volumes:
  docuseal_data:
    external: true
    name: docuseal_data

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}
