version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - "discovery.type=single-node"
    deploy:
      replicas: 1
    networks:
      - monitoring

  logstash:
    image: logstash:8.6.2
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
    networks:
      - {{network_name}}

  kibana:
    image: kibana:8.6.2
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kibana.rule=Host(`{{kibana_url}}`)"
        - "traefik.http.services.kibana.loadbalancer.server.port=5601"
    networks:
      - monitoring

networks:
  {{network_name}}:
    external: true
