version: "3.7"
services:

  krayin:
    image: webkul/krayin:2.0.4

    volumes:
      - krayin_data:/var/www/html/laravel-crm

    networks:
      - {{network_name}}
      
    environment:
      ## Dados de acesso
      - krayin_PUBLIC_URL=https://{{krayincrm_url}}
      - APP_URL=https://{{krayincrm_url}}
      - krayin_CADDY_ADDRESSES=:80
      - APP_ENV=production
      - APP_KEY={{krayincrm_secret_key}}
      - APP_DEBUG=false
      - APP_TIMEZONE=America/Sao_Paulo
      - APP_LOCALE=pt_BR
      - APP_CURRENCY=BRL
      - SANCTUM_STATEFUL_DOMAINS=https://{{krayincrm_url}}/public

      ## Configuração do Banco de Dados
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=krayin
      - DB_USERNAME=root
      - DB_PASSWORD=$senha_mysql
      - DB_PREFIX=

      ## Configurações de e-mail
      - MAIL_MAILER=smtp
      - MAIL_FROM_ADDRESS={{krayincrm_email}}
      - MAIL_USERNAME={{krayincrm_email_username}}
      - MAIL_PASSWORD={{krayincrm_email_password}}
      - MAIL_HOST={{krayincrm_smtp_email}}
      - MAIL_PORT={{krayincrm_smtp_port}}
      - MAIL_ENCRYPTION={{krayincrm_smtp_secure}}
      - MAIL_FROM_NAME="Helpdesk"

      ## Configurações de Cache e Sessão
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120

      ## Configurações de Redis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.krayin.rule=Host(`{{krayincrm_url}}`) && PathPrefix(`/`)
        - traefik.http.services.krayin.loadbalancer.server.port=80
        - traefik.http.routers.krayin.service=krayin
        - traefik.http.routers.krayin.tls.certresolver=letsencryptresolver
        - traefik.http.routers.krayin.entrypoints=websecure
        - traefik.http.routers.krayin.tls=true

volumes:
  krayin_data:
    external: true
    name: krayin_data

networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
