version: "3.8"
services:

  langflow:
    image: langflowai/langflow:v1.0.19.post2

    volumes:
      - langflow_data:/app/langflow

    networks:
      - {{network_name}}

    environment:
      ## Dados de acesso
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_SUPERUSER={{langflow_username}}
      - LANGFLOW_SUPERUSER_PASSWORD={{langflow_password}}
      - LANGFLOW_HOST=0.0.0.0
      - BACKEND_URL=https://{{langflow_url}}

      ## Secret Key
      ## Gere em: https://www.uuidgenerator.net/api/version1
      - LANGFLOW_SECRET_KEY={{langflow_secret_key}}

      ## Signup Settings
      - LANGFLOW_NEW_USER_IS_ACTIVE=false

      ## Postgres
      - LANGFLOW_DATABASE_URL=postgresql://postgres:{{postgres_password}}@postgres:5432/langflow

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.langflow.rule=Host(`{{langflow_url}}`) ## Url da aplicação
        - traefik.http.services.langflow.loadBalancer.server.port=7860
        - traefik.http.routers.langflow.service=langflow
        - traefik.http.routers.langflow.entrypoints=websecure
        - traefik.http.routers.langflow.tls.certresolver=letsencryptresolver

volumes:
  langflow_data:
    external: true
    name: langflow_data

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}