version: "3.7"
services:

  metabase:
    image: metabase/metabase:latest
    hostname: metabase

    volumes:
      - metabase_data:/metabase3-data

    networks:
      - {{network_name}}

    environment:
      - MB_SITE_URL=https://{{url_metabase}}
      - MB_REDIRECT_ALL_REQUESTS_TO_HTTPS=true
      - MB_JETTY_PORT=3000
      - MB_JETTY_HOST=0.0.0.0

      - MB_DB_MIGRATION_LOCATION=none
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS={{postgres_password}}
      - MB_DB_HOST=postgres
      - MB_AUTOMIGRATE=false
    
    healthcheck:
      test: curl --fail -I http://127.0.0.1:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.metabase.rule=Host(`{{url_metabase}}`)
        - traefik.http.services.metabase.loadbalancer.server.port=3000
        - traefik.http.routers.metabase.service=metabase
        - traefik.http.routers.metabase.entrypoints=websecure
        - traefik.http.routers.metabase.tls=true
        - traefik.http.routers.metabase.tls.certresolver=letsencryptresolver

volumes:
  metabase_data:
    external: true
    name: metabase_data

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}