version: "3.7"
services:

  mysql:
    image: percona/percona-server:{{image_version}}
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--sql-mode=",
        "--default-authentication-plugin=caching_sha2_password",
        "--max-allowed-packet=512MB",
      ]

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - {{network_name}}

    ports:
      - 3306:3306

    environment:
      ## MYSQL Password
      - MYSQL_USER=mysql
      - MYSQL_ROOT_PASSWORD={{db_password}}

      ## TimeZone
      - TZ=America/Sao_Paulo
    
    healthcheck:
      test: mysql --user=mysql --password={{db_password}} --silent --execute "SHOW DATABASES"
      interval: 2m
      timeout: 10s
      retries: 5
      start_period: 40s

    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  mysql_data:
    external: true
    name: mysql_data

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}