version: "3.7"

services:
  n8n_editor:
    image: n8nio/n8n:latest
    command: start

    networks:
      - {{network_name}}

    environment:
      ## Dados do postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD={{postgres_password}}

      ## Encryption Key
      - N8N_ENCRYPTION_KEY={{n8n_encryption_key}}

      ## Url do N8N
      - N8N_HOST={{url_editor}}
      - N8N_EDITOR_BASE_URL=https://{{n8n_editor_url}}/ 
      - WEBHOOK_URL=https://{{n8n_webhook_url}}/
      - N8N_PROTOCOL=https

      ## Node mode
      - NODE_ENV=production

      ## Execution node
      - EXECUTIONS_MODE=queue

      ## Community Nodes
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes

      ## SMTP
      - N8N_SMTP_SENDER={{n8n_smtp_from_email}}
      - N8N_SMTP_HOST={{n8n_smtp_host}}
      - N8N_SMTP_PORT={{n8n_smtp_port}}
      - N8N_SMTP_USER={{n8n_smtp_username}}
      - N8N_SMTP_PASS={{n8n_smtp_password}}
      - N8N_SMTP_SSL={{n8n_smtp_secure}}

      ## Redis
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336

      ## Timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_editor.rule=Host(`{{n8n_editor_url}}`) ## Url do Editor do N8N
        - traefik.http.routers.n8n_editor.entrypoints=websecure
        - traefik.http.routers.n8n_editor.priority=1
        - traefik.http.routers.n8n_editor.tls.certresolver=letsencryptresolver
        - traefik.http.routers.n8n_editor.service=n8n_editor
        - traefik.http.services.n8n_editor.loadbalancer.server.port=5678
        - traefik.http.services.n8n_editor.loadbalancer.passHostHeader=1

  n8n_webhook:
    image: n8nio/n8n:latest ## Versão do N8N
    command: webhook

    networks:
      - {{network_name}} ## Nome da rede interna

    environment:
      ## Dados do postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD={{postgres_password}}

      ## Encryption Key
      - N8N_ENCRYPTION_KEY={{n8n_encryption_key}}

      ## Url do N8N
      - N8N_HOST={{url_editor}}
      - N8N_EDITOR_BASE_URL=https://{{n8n_editor_url}}/
      - WEBHOOK_URL=https://{{n8n_webhook_url}}/
      - N8N_PROTOCOL=https

      ## Node Mode
      - NODE_ENV=production

      ## Execution mode
      - EXECUTIONS_MODE=queue

      ## Community Nodes
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes

      ## SMTP
      - N8N_SMTP_SENDER={{n8n_smtp_from_email}}
      - N8N_SMTP_HOST={{n8n_smtp_host}}
      - N8N_SMTP_PORT={{n8n_smtp_port}}
      - N8N_SMTP_USER={{n8n_smtp_username}}
      - N8N_SMTP_PASS={{n8n_smtp_password}}
      - N8N_SMTP_SSL={{n8n_smtp_secure}}

      ## Redis
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336

      ## Timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_webhook.rule=(Host(`{{n8n_webhook_url}}`))
        - traefik.http.routers.n8n_webhook.entrypoints=websecure
        - traefik.http.routers.n8n_webhook.priority=1
        - traefik.http.routers.n8n_webhook.tls.certresolver=letsencryptresolver
        - traefik.http.routers.n8n_webhook.service=n8n_webhook
        - traefik.http.services.n8n_webhook.loadbalancer.server.port=5678
        - traefik.http.services.n8n_webhook.loadbalancer.passHostHeader=1

  n8n_worker:
    image: n8nio/n8n:latest ## Versão do N8N
    command: worker --concurrency=10

    networks:
      - {{network_name}}

    environment:
      ## Postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD={{postgres_password}}

      ## Encryption Key
      - N8N_ENCRYPTION_KEY={{n8n_encryption_key}}

      ## N8N Url
      - N8N_HOST={{url_editor}}
      - N8N_EDITOR_BASE_URL=https://{{n8n_editor_url}}/
      - WEBHOOK_URL=https://{{n8n_webhook_url}}/
      - N8N_PROTOCOL=https

      ## Node mode
      - NODE_ENV=production

      ## Execution mode
      - EXECUTIONS_MODE=queue

      ## Community Nodes
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes

      ## SMTP
      - N8N_SMTP_SENDER={{n8n_smtp_from_email}}
      - N8N_SMTP_HOST={{n8n_smtp_host}}
      - N8N_SMTP_PORT={{n8n_smtp_port}}
      - N8N_SMTP_USER={{n8n_smtp_username}}
      - N8N_SMTP_PASS={{n8n_smtp_password}}
      - N8N_SMTP_SSL={{n8n_smtp_secure}}

      ## Redis
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336

      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}