version: "3.7"
services:
  nocobase:
    image: nocobase/nocobase:latest

    volumes:
      - nocobase_storage:/app/nocobase/storage

    networks:
      - {{network_name}}

    environment:
      ## Nocobase
      - INIT_ROOT_EMAIL={{nocobase_email}}
      - INIT_ROOT_PASSWORD={{nocobase_password}}
      - INIT_ROOT_NICKNAME={{nocobase_username}}
      - INIT_ROOT_USERNAME={{nocobase_username}}

      ## Postgres
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=nocobase
      - DB_USER=postgres
      - DB_PASSWORD={{postgres_password}}

      ## Paths de URL
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
      - API_BASE_PATH=/api/

      ## Encryption Key
      - APP_KEY={{nocobase_encryption_key}}
      - ENCRYPTION_FIELD_KEY={{nocobase_encryption_key}}

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.nocobase.rule=Host(`{{nocobase_url}}`)
        - traefik.http.services.nocobase.loadbalancer.server.port=80
        - traefik.http.routers.nocobase.service=nocobase
        - traefik.http.routers.nocobase.tls.certresolver=letsencryptresolver
        - traefik.http.routers.nocobase.entrypoints=websecure
        - traefik.http.routers.nocobase.tls=true

volumes:
  nocobase_storage:
    external: true

networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
