version: "3.7"
services:
  ntfy:
    image: binwiederhier/ntfy:latest
    command:
      - serve

    volumes:
      - ntfy_cache:/var/cache/ntfy
      - ntfy_etc:/etc/ntfy

    networks:
      - {{network_name}}

    environment:
      - TZ=UTC

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.ntfy.rule=Host(`{{ntfy_url}}`)
        - traefik.http.services.ntfy.loadbalancer.server.port=80
        - traefik.http.routers.ntfy.service=ntfy
        - traefik.http.routers.ntfy.tls.certresolver=letsencryptresolver
        - traefik.http.routers.ntfy.entrypoints=websecure
        - traefik.http.middlewares.ntfy-auth.basicauth.users={{hashed_password}}
        - traefik.http.routers.ntfy.middlewares=ntfy-auth
        - traefik.http.routers.ntfy.tls=true

volumes:
  ntfy_cache:
    external: true
    name: ntfy_cache
  ntfy_etc:
    external: true
    name: ntfy_etc

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}
