version: "3.7"
services:

  ollama:
    image: ollama/ollama:latest

    volumes:
      - ollama_data:/root/.ollama

    networks:
      - {{network_name}}

    #ports:
    #  - 11434:11434

    environment:
      - OLLAMA_HOST=0.0.0.0

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=1
        - traefik.http.routers.ollama.rule=Host(`{{ollama_api_url}}`)
        - traefik.http.routers.ollama.entrypoints=websecure
        - traefik.http.routers.ollama.priority=1
        - traefik.http.routers.ollama.tls.certresolver=letsencryptresolver
        - traefik.http.routers.ollama.service=ollama
        - traefik.http.services.ollama.loadbalancer.server.port=11434
        - traefik.http.services.ollama.loadbalancer.passHostHeader=1

  openwebui:
    image: ghcr.io/open-webui/open-webui:main

    volumes:
      - open_webui:/app/backend/data

    networks:
      - $nome_rede_interna

    #ports:
    #  - 8085:8080

    environment:
      - OLLAMA_BASE_URL=https://{{ollama_api_url}}
      - WEBUI_SECRET_KEY={{webui_secret_key}}

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.openwebui.rule=Host(`{{ollama_url}}`)
        - traefik.http.routers.openwebui.entrypoints=websecure
        - traefik.http.routers.openwebui.priority=1
        - traefik.http.routers.openwebui.tls.certresolver=letsencryptresolver
        - traefik.http.routers.openwebui.service=openwebui
        - traefik.http.services.openwebui.loadbalancer.server.port=8080
        - traefik.http.services.openwebui.loadbalancer.passHostHeader=true

volumes:
  ollama_data:
    external: true
    name: ollama_data
  open_webui:
    external: true
    name: open_webui
  
networks:
  {{network_name}}:
    external: true
    name: {{network_name}}