version: "3.7"
services:

  pgvector:
    image: pgvector/pgvector:{{image_version}}

    volumes:
      - pgvector:/var/lib/postgresql/data

    networks:
      - {{network_name}}

    ports:
      - 5433:5432

    environment:
      ## Senha do postgres 
      - POSTGRES_PASSWORD={{db_password}}

      ## Max connections
      #- PG_MAX_CONNECTIONS=500

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  pgvector:
    external: true
    name: pgvector

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}