version: "3.7"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    command: ["apache2-foreground"]

    networks:
      - {{network_name}}

    environment:
      ## MySQL
      - PMA_HOSTS={{phpadmin_url}}
      - PMA_PORT=3306
      
      ## Credentials
      - PMA_USER={{phpadmin_username}}
      - PMA_PASSWORD={{phpadmin_password}}
      - PMA_ABSOLUTE_URI=https://{{phpadmin_url}}
      
      ## Upload limit
      - UPLOAD_LIMIT=10M

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.phpmyadmin.rule=Host(`{{phpadmin_url}}`)
        - traefik.http.routers.phpmyadmin.entrypoints=web,websecure
        - traefik.http.routers.phpmyadmin.tls.certresolver=letsencryptresolver
        - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
        - traefik.http.routers.phpmyadmin.service=phpmyadmin

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}
