version: "3.7"

services:
  qdrant:
    image: qdrant/qdrant:latest

    networks:
      - {{network_name}}

    ports:
      - 6333:6333
      - 6334:6334

    volumes:
      - /opt/stackme/stacks/qdrant_data:/qdrant/storage

    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.qdrant.rule=Host(`{{qdrant_url}}`)"
        - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
        - "traefik.http.routers.qdrant.entrypoints=websecure"
        - "traefik.http.routers.qdrant.service=qdrant"
        - "traefik.http.routers.qdrant.tls=true"
        - "traefik.http.routers.qdrant.tls.certresolver=letsencryptresolver"

volumes:
  qdrant_data:
    external: true
    name: qdrant_data

networks:
  mynetwork:
    name: {{network_name}}
    external: true