version: "3.7"
services:

  quepasa:
    image: deividms/quepasa:latest ## Imagem/versão do Quepasa
      
    volumes:
      - quepasa_volume:/opt/quepasa

    networks:
      - {{network_name}}

    environment:
      ## Dados de acesso
      - DOMAIN={{quepasa_url}}

      ## Email Quepasa
      - EMAIL=$email_quepasa
      - QUEPASA_BASIC_AUTH_USER={{quepasa_email_username}}
      - QUEPASA_BASIC_AUTH_PASSWORD={{quepasa_email_password}}

      ## Titulo no celular
      - APP_TITLE={{quepasa_title}}

      ## TimeZone
      - TZ=America/Sao_Paulo

      ## Configurações para o WhatsApp
      - GROUPS=true
      - BROADCASTS=false
      - READRECEIPTS=forcedfalse
      - CALLS=true
      - READUPDATE=false
      - LOGLEVEL=DEBUG

      ## Configurações quepasa
      - QUEPASA_HOST_NAME=Quepasa
      - QUEPASA_MEMORY_LIMIT=4096M
      - WEBSOCKETSSL=true
      - REMOVEDIGIT9=true
      - SIGNING_SECRET=$key_quepasa

      ## Webhook
      #- WEBHOOK_QUEPASA={{n8n_webhook_url}}/webhook/quepasa
      #- WEBHOOK_TESTE_QUEPASA={{n8n_webhook_url}}/webhook-test/quepasa
            
      ## Ports
      - QUEPASA_EXTERNAL_PORT=31000
      - QUEPASA_INTERNAL_PORT=31000
      - WEBAPIPORT=31000

      ## Database
      - DEBUGREQUESTS=false
      - SYNOPSISLENGTH=500
      - METRICS_HOST=
      - METRICS_PORT=9392
      - MIGRATIONS=/builder/migrations
      - DEBUGJSONMESSAGES=false
      - HTTPLOGS=false

      ## Whatsmeow Settings
      - WHATSMEOW_LOGLEVEL=WARN
      - WHATSMEOW_DBLOGLEVEL=WARN

      ## Env Mode
      - APP_ENV=production
      - NODE_ENV=production

    deploy:
      mode: replicated
      replicas: 1
      placement:
          constraints:
          - node.role == manager
      resources:
          limits:
              cpus: "2"
              memory: 2096M
                      
      labels:
        - traefik.enable=true
        - traefik.http.routers.quepasa.rule=Host(`{{quepasa_url}}`)
        - traefik.http.routers.quepasa.tls=true
        - traefik.http.routers.quepasa.entrypoints=web,websecure
        - traefik.http.routers.quepasa.tls.certresolver=letsencryptresolver
        - traefik.http.routers.quepasa.service=quepasa
        - traefik.http.routers.quepasa.priority=1      
        - traefik.http.middlewares.quepasa.headers.SSLRedirect=true
        - traefik.http.middlewares.quepasa.headers.STSSeconds=315360000
        - traefik.http.middlewares.quepasa.headers.browserXSSFilter=true
        - traefik.http.middlewares.quepasa.headers.contentTypeNosniff=true
        - traefik.http.middlewares.quepasa.headers.forceSTSHeader=true
        - traefik.http.middlewares.quepasa.headers.SSLHost=\${QUEPASA_HOST}
        - traefik.http.middlewares.quepasa.headers.STSIncludeSubdomains=true
        - traefik.http.middlewares.quepasa.headers.STSPreload=true
        - traefik.http.services.quepasa.loadbalancer.server.port=31000
        - traefik.http.services.quepasa.loadbalancer.passHostHeader=true              

volumes:
  quepasa_volume:
    external: true
    name: quepasa_volume

networks:
  {{network_name}}:
    external: true
    name: {{network_name}} 
