version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server

    hostname: rabbitmq

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - {{network_name}}
    ports:
      - 5672:5672
      - 15672:15672

    environment:
      RABBITMQ_DEFAULT_USER: {{rabbitmq_username}}
      RABBITMQ_DEFAULT_PASS: {{rabbitmq_password}}
      RABBITMQ_ERLANG_COOKIE: {{cookie_key}}
      RABBITMQ_DEFAULT_VHOST: "/"

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.rabbitmq.rule=Host(`{{url_rabbitmq}}`)
        - traefik.http.routers.rabbitmq.entrypoints=websecure
        - traefik.http.routers.rabbitmq.tls.certresolver=letsencryptresolver
        - traefik.http.routers.rabbitmq.service=rabbitmq
        - traefik.http.services.rabbitmq.loadbalancer.server.port=15672

volumes:
  rabbitmq_data:
    external: true

networks:
  {{network_name}}:
    external: true