version: '3.7'

services:
  trino:
    image: trinodb/trino:latest
    deploy:
      replicas: 1
    networks:
      - {{network_name}}

  superset:
    image: apache/superset:latest
    depends_on:
      - trino
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.superset.rule=Host(`{{superset_url}}`)"
        - "traefik.http.services.superset.loadbalancer.server.port=8088"
    networks:
      - {{network_name}}

volumes:
  minio-data:

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}
