version: "3.7"
services:
  traccar:
    image: traccar/traccar:latest
    
    volumes:
      - /opt/traccar/logs:/opt/traccar/logs:rw
      - /opt/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro
      - traccar_data:/opt/traccar/

    networks:
      - {{network_name}}

    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g -Djava.net.preferIPv4Stack=true
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.traccar.rule=Host(`{{traccar_url}}`)
        - traefik.http.services.traccar.loadbalancer.server.port=8082
        - traefik.http.routers.traccar.service=traccar
        - traefik.http.routers.traccar.tls.certresolver=letsencryptresolver
        - traefik.http.routers.traccar.entrypoints=websecure
        - traefik.http.routers.traccar.tls=true

  traccar_db:
    image: mysql:8.0

    volumes:
      - traccar_db:/var/lib/mysql

    networks:
      - {{network_name}}

    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=traccar
      - MYSQL_USER=traccar
      - MYSQL_PASSWORD={{mysql_password}}

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  traccar_data:
    external: true
    name: traccar_data
  traccar_db:
    external: true
    name: traccar_db
    
networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
