version: "3.7"
services:
  transcrevezap:
    image: impacteai/transcrevezap:latest
    command: ./start.sh

    networks:
      - {{network_name}}

    environment:
      ## Configurações de acesso
      - MANAGER_USER={{transcrevezap_username}}
      - MANAGER_PASSWORD={{transcrevezap_password}}

      ## Configurações Globais
      - API_DOMAIN={{transcrevezap_api}}
      - UVICORN_PORT=8005
      - UVICORN_HOST=0.0.0.0
      - UVICORN_RELOAD=true
      - UVICORN_WORKERS=1

      ## Configurações do Redis
      - REDIS_HOST=redis_transcrevezap
      - REDIS_PORT=6380

      ## Configurações de Debug
      - DEBUG_MODE=false
      - LOG_LEVEL=INFO

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.transcrevezap.rule=Host(\`{{transcrevezap_api_url}}\`)
        - traefik.http.routers.transcrevezap.entrypoints=websecure
        - traefik.http.routers.transcrevezap.tls.certresolver=letsencryptresolver
        - traefik.http.services.transcrevezap.loadbalancer.server.port=8005
        - traefik.http.services.transcrevezap.loadbalancer.passHostHeader=true
        - traefik.http.routers.transcrevezap.service=transcrevezap
        - traefik.http.middlewares.traefik-compress.compress=true
        - traefik.http.routers.transcrevezap.middlewares=traefik-compress
        - traefik.http.routers.transcrevezap_manager.rule=Host(\`{{transcrevezap_url}}\`)
        - traefik.http.routers.transcrevezap_manager.entrypoints=websecure
        - traefik.http.routers.transcrevezap_manager.tls.certresolver=letsencryptresolver
        - traefik.http.routers.transcrevezap_manager.service=transcrevezap_manager
        - traefik.http.services.transcrevezap_manager.loadbalancer.server.port=8501

  redis_transcrevezap:
    image: redis:6
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6380"
      ]

    volumes:
      - redis_transcrevezap_data:/data

    networks:
      - {{network_name}}

volumes:
  redis_transcrevezap_data:
    external: true
    name: redis_transcrevezap_data

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}
