version: "3.7"
services:
  transcrevezap:
    image: impacteai/transcrevezap:latest
    command: ./start.sh

    networks:
      - {{network_name}}

    environment:
      ## Credentials
      - MANAGER_USER={{transcrevezap_username}}
      - MANAGER_PASSWORD={{transcrevezap_password}}

      ## Settings
      - API_DOMAIN={{transcrevezap_api_url}}
      - UVICORN_PORT=8005
      - UVICORN_HOST=0.0.0.0
      - UVICORN_RELOAD=true
      - UVICORN_WORKERS=1

      ## Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      ## Debug
      - DEBUG_MODE=true
      - LOG_LEVEL=INFO

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.transcrevezap.rule=Host(`{{transcrevezap_api_url}}`)
        - traefik.http.routers.transcrevezap.entrypoints=websecure
        - traefik.http.routers.transcrevezap.tls.certresolver=letsencryptresolver
        - traefik.http.services.transcrevezap.loadbalancer.server.port=8005
        - traefik.http.services.transcrevezap.loadbalancer.passHostHeader=true
        - traefik.http.routers.transcrevezap.service=transcrevezap
        - traefik.http.middlewares.traefik-compress.compress=true
        - traefik.http.routers.transcrevezap.middlewares=traefik-compress
        - traefik.http.routers.transcrevezap_manager.rule=Host(`{{transcrevezap_url}}`)
        - traefik.http.routers.transcrevezap_manager.entrypoints=websecure
        - traefik.http.routers.transcrevezap_manager.tls.certresolver=letsencryptresolver
        - traefik.http.routers.transcrevezap_manager.service=transcrevezap_manager
        - traefik.http.services.transcrevezap_manager.loadbalancer.server.port=8501

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}
