version: "3.7"
services:

  vaultwarden:
    image: vaultwarden/server:latest

    volumes:
      - vaultwarden_data:/data

    networks:
      - $nome_rede_interna

    #ports:
    #  - 1973:80

    environment:
      ## Dominio do Dashboard
      - DOMAIN=https://{{vaultwarden_url}}

      ## Permitir novos registros
      - SIGNUPS_ALLOWED=true

      ## Dados do SMTP
      - SMTP_FROM={{vaultwarden_email}}
      - SMTP_USERNAME={{vaultwarden_smtp_username}}
      - SMTP_PASSWORD={{vaultwarden_smtp_password}}
      - SMTP_HOST={{vaultwarden_smtp_host}}
      - SMTP_PORT={{vaultwarden_smtp_port}}
      - SMTP_SECURITY={{vaultwarden_smtp_secure}}

      ## Configuração do Websocket
      - WEBSOCKET_ENABLED=true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vaultwarden.rule=Host(`{{vaultwarden_url}}`)"
        - "traefik.http.routers.vaultwarden.service=vaultwarden"
        - "traefik.http.routers.vaultwarden.entrypoints=websecure"
        - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
        - "traefik.http.routers.vaultwarden.tls=true"
        - "traefik.http.routers.vaultwarden.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.vaultwarden.loadbalancer.passhostheader=true"
        - "traefik.http.routers.vaultwarden.middlewares=compresstraefik"
        - "traefik.http.middlewares.compresstraefik.compress=true"
        - "traefik.docker.network={{network_name}}"

volumes:
  vaultwarden_data:
    external: true
    name: vaultwarden_data

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}
