version: "3.7"
services:
  weaviate:
    image: semitechnologies/weaviate:latest

    volumes:
      - weaviate_data:/var/lib/weaviate

    networks:
      - {{network_name}}

    environment:
      ## Settings
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=false
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=node1

      ## Authentication
      - AUTHENTICATION_APIKEY_ENABLED=true
      - AUTHENTICATION_APIKEY_ALLOWED_KEYS={{weaviate_token}}
      - AUTHENTICATION_APIKEY_USERS=
      - AUTHORIZATION_ADMINLIST_ENABLED=true
      - AUTHORIZATION_ADMINLIST_USERS=

      ## Telemetry
      - DISABLE_TELEMETRY=true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 4096M

      labels:
        - traefik.enable=true
        - traefik.http.routers.weaviate.rule=Host(\`{{weaviate_url}}\`)
        - traefik.http.routers.weaviate.entrypoints=websecure
        - traefik.http.routers.weaviate.tls.certresolver=letsencryptresolver 

volumes:
  weaviate_data:
    external: true
    name: weaviate

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}