version: "3.7"
services:
  wordpress_{{wordpress_site_name}}:
    image: wordpress:latest

    volumes:
      - wordpress_{{wordpress_site_name}}:/var/www/html
      - wordpress_{{wordpress_site_name}}_php:/usr/local/etc/php

    networks:
      - {{network_name}}

    environment:
      ## Dados do Mysql
      - WORDPRESS_DB_NAME={{wordpress_site_name}}
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PORT=3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD={{mysql_password}}

      ## Redis
      - WP_REDIS_HOST=redis
      - WP_REDIS_PORT=6379
      - WP_REDIS_DATABASE=6

      ## Url do Wordpress
      - VIRTUAL_HOST={{wordpress_url}}

      ## Localização
      - WP_LOCALE=pt_BR

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.wordpress_{{wordpress_site_name}}.rule=Host(`{{wordpress_url}}`)
        - traefik.http.routers.wordpress_{{wordpress_site_name}}.entrypoints=websecure
        - traefik.http.routers.wordpress_{{wordpress_site_name}}.tls.certresolver=letsencryptresolver
        - traefik.http.routers.wordpress_{{wordpress_site_name}}.service=wordpress_{{wordpress_site_name}}
        - traefik.http.services.wordpress_{{wordpress_site_name}}.loadbalancer.server.port=80
        - traefik.http.services.wordpress_{{wordpress_site_name}}.loadbalancer.passHostHeader=true

volumes:
  wordpress_{{wordpress_site_name}}:
    external: true
    name: wordpress_{{wordpress_site_name}}
  wordpress_${nome_site_wordpress}_php:
    external: true
    name: wordpress_{{wordpress_site_name}}_php

networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
