version: "3.7"
services:
  baserow:
    image: baserow/baserow:latest ## Versão do Baserow

    volumes:
      - baserow_data:/baserow/data

    networks:
      - {{network_name}}

    environment:
      ## Baserow Url
      - BASEROW_PUBLIC_URL=https://{{baserow_url}}

      ## Porta do baserow
      - BASEROW_CADDY_ADDRESSES=:80

      ## Dados SMTP
      - EMAIL_SMTP=true ## Unable/enable SMTP 
      - FROM_EMAIL={{baserow_smtp_from_email}} ## Email
      - EMAIL_SMTP_USER={{baserow_smtp_username}} ## Username
      - EMAIL_SMTP_PASSWORD={{baserow_smtp_password}} ## SMTP Password
      - EMAIL_SMTP_HOST={{baserow_smtp_host}} ## SMTP Host
      - EMAIL_SMTP_PORT={{baserow_smtp_port}} ## SMTP port
      - EMAIL_SMTP_USE_SSL={{baserow_smtp_secure}}

      ## Dados Redis
      - REDIS_URL=redis://redis:6379/11

      ## Dados postgres:
      - DATABASE_URL=postgresql://postgres:{{postgres_password}}@postgres:5432/baserow

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.baserow.rule=Host(`{{baserow_url}}`)
        - traefik.http.services.baserow.loadbalancer.server.port=80
        - traefik.http.routers.baserow.service=baserow
        - traefik.http.routers.baserow.tls.certresolver=letsencryptresolver
        - traefik.http.routers.baserow.entrypoints=websecure
        - traefik.http.routers.baserow.tls=true

volumes:
  baserow_data:
    external: true
    name: baserow_data

networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
