version: "3.7"
services:
  excalidraw:
    image: excalidraw/excalidraw:latest

    volumes:
      - excalidraw_data:/data

    networks:
      - {{network_name}}

    environment:
      - EXCALIDRAW_PORT=80
      - NODE_ENV=development

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.excalidraw.rule=Host(`{{excalidraw_url}}`)
        - traefik.http.services.excalidraw.loadbalancer.server.port=80
        - traefik.http.routers.excalidraw.service=excalidraw
        - traefik.http.routers.excalidraw.tls.certresolver=letsencryptresolver
        - traefik.http.routers.excalidraw.entrypoints=websecure
        - traefik.http.routers.excalidraw.tls=true

volumes:
  excalidraw_data:
    external: true
    name: excalidraw_data

networks:
  {{network_name}}:
    name: {{network_name}}
    external: true
