version: "3.7"
services:
  lowcoder_api:
    image: lowcoderorg/lowcoder-ce-api-service:latest

    networks:
      - {{network_name}}

    environment:
      - LOWCODER_PUID=9001
      - LOWCODER_PGID=9001

      ## Dados MongoDB
      - LOWCODER_MONGODB_URL=mongodb://{{mongodb_username}}:{{mongodb_password}}@mongodb:27017/lowcoder?authSource=admin&readPreference=primary&ssl=false&directConnection=true

      ## Dados Redis
      - LOWCODER_REDIS_URL=redis://redis:6379

      ## Dominio
      - LOWCODER_NODE_SERVICE_URL=http://lowcoder_node:6060

      ## Configurações
      - LOWCODER_MAX_QUERY_TIMEOUT=120
      - LOWCODER_EMAIL_AUTH_ENABLED=true
      - LOWCODER_EMAIL_SIGNUP_ENABLED=true ## true = allow signups
      - LOWCODER_CREATE_WORKSPACE_ON_SIGNUP=true ## true = allow signups
      - LOWCODER_WORKSPACE_MODE=SAAS

      ## Encryption lowcoder_encryption_key
      - LOWCODER_DB_ENCRYPTION_PASSWORD={{lowcoder_encryption_key}} ## hash Encryption
      - LOWCODER_DB_ENCRYPTION_SALT={{lowcoder_encryption_salt}} ## hash Encryption
      - LOWCODER_API_KEY_SECRET={{lowcoder_api_secret_key}} # hash Encryption

      ## Outras configurações
      - LOWCODER_CORS_DOMAINS=*
      - LOWCODER_MAX_ORGS_PER_USER=100
      - LOWCODER_MAX_MEMBERS_PER_ORG=1000
      - LOWCODER_MAX_GROUPS_PER_ORG=100
      - LOWCODER_MAX_APPS_PER_ORG=1000
      - LOWCODER_MAX_DEVELOPERS=50

      ## Dados SMTP
      - LOWCODER_ADMIN_SMTP_HOST={{lowcoder_smtp_host}}
      - LOWCODER_ADMIN_SMTP_PORT={{lowcoder_smtp_port}}
      - LOWCODER_ADMIN_SMTP_USERNAME={{lowcoder_smtp_username}}
      - LOWCODER_ADMIN_SMTP_PASSWORD={{lowcoder_smtp_password}}
      - LOWCODER_ADMIN_SMTP_AUTH=true
      - LOWCODER_ADMIN_SMTP_SSL_ENABLED={{lowcoder_smtp_secure}}
      - LOWCODER_ADMIN_SMTP_STARTTLS_ENABLED={{lowcoder_smtp_secure}}
      - LOWCODER_ADMIN_SMTP_STARTTLS_REQUIRED={{lowcoder_smtp_secure}}
      - LOWCODER_EMAIL_NOTIFICATIONS_SENDER={{lowcoder_smtp_from_email}}
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

  lowcoder_node:
    image: lowcoderorg/lowcoder-ce-node-service:latest

    networks:
      - {{network_name}}

    depends_on:
      - lowcoder_api

    environment:
      - LOWCODER_PUID=9001
      - LOWCODER_PGID=9001
      - LOWCODER_API_SERVICE_URL=http://lowcoder_api:8080

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

  lowcoder_frontend:
    image: lowcoderorg/lowcoder-ce-frontend:latest

    volumes:
      - lowcoder_assets:/lowcoder/assets

    depends_on:
      - lowcoder_api
      - lowcoder_node

    networks:
      - {{network_name}}

    environment:
      - LOWCODER_PUID=9001
      - LOWCODER_PGID=9001
      - LOWCODER_MAX_REQUEST_SIZE=20m
      - LOWCODER_MAX_QUERY_TIMEOUT=120
      - LOWCODER_API_SERVICE_URL=http://lowcoder_api:8080
      - LOWCODER_NODE_SERVICE_URL=http://lowcoder_node:6060

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager  
      labels:
        - traefik.enable=true
        - traefik.http.routers.lowcoder.rule=Host(`{{lowcoder_url}}`) && PathPrefix(`/`)
        - traefik.http.services.lowcoder.loadbalancer.server.port=3000
        - traefik.http.routers.lowcoder.service=lowcoder
        - traefik.http.routers.lowcoder.entrypoints=websecure
        - traefik.http.routers.lowcoder.tls.certresolver=letsencryptresolver
        - traefik.http.routers.lowcoder.tls=true

volumes:
  lowcoder_assets:
    external: true
    name: lowcoder_assets

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}