version: "3.7"
services:
  uptimekuma:
    image: louislam/uptime-kuma:latest

    volumes:
      - uptimekuma_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - {{network_name}}

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.uptimekuma.rule=Host(`{{uptimekuma_url}}`)
        - traefik.http.routers.uptimekuma.entrypoints=websecure
        - traefik.http.routers.uptimekuma.tls.certresolver=letsencryptresolver
        - traefik.http.services.uptimekuma.loadBalancer.server.port=3001
        - traefik.http.routers.uptimekuma.service=uptimekuma

volumes:
  uptimekuma_data:
    external: true
    name: uptimekuma_data

networks:
  {{network_name}}:
    external: true
    name: {{network_name}}
