version: "3.7"
services:
  zep_nlp:
    image: ghcr.io/getzep/zep-nlp-server:latest

    networks:
      - {{network_name}}
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  zep_app:
    image: ghcr.io/getzep/zep:latest
    
    volumes:
      - /opt/stackme/stacks/zep/config.yaml:/app/config.yaml

    networks:
      - {{network_name}}

    environment:
      ## Postgres
      - ZEP_STORE_TYPE=postgres
      - ZEP_STORE_POSTGRES_DSN=postgres://postgres:{{pgvector_password}}@pgvector:5432/zep?sslmode=disable

      ## Auth
      - ZEP_AUTH_SECRET={{zep_api_key}}

      ## OpenAI
      - ZEP_OPENAI_API_KEY={{zep_openai_api_key}}

      ## NLP
      - ZEP_NLP_SERVER_URL=http://zep_nlp:5557

      ## Extraction settings
      - ZEP_EXTRACTORS_DOCUMENTS_EMBEDDINGS_SERVICE=openai
      - ZEP_EXTRACTORS_DOCUMENTS_EMBEDDINGS_DIMENSIONS=1536
      - ZEP_EXTRACTORS_MESSAGES_EMBEDDINGS_SERVICE=openai
      - ZEP_EXTRACTORS_MESSAGES_EMBEDDINGS_DIMENSIONS=1536
      - ZEP_EXTRACTORS_MESSAGES_SUMMARIZER_EMBEDDINGS_SERVICE=openai
      - ZEP_EXTRACTORS_MESSAGES_SUMMARIZER_EMBEDDINGS_DIMENSIONS=1536

      ## Graphiti
      - ZEP_GRAPHITI_URL=http://zep_graphiti:8003

      ## Degub:
      - ZEP_LOG_LEVEL=debug
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.zep.rule=Host(`{{zep_url}}`)
        - traefik.http.routers.zep.entrypoints=websecure
        - traefik.http.routers.zep.tls.certresolver=letsencryptresolver
        - traefik.http.services.zep.loadbalancer.server.port=8000
        - traefik.http.services.zep.loadbalancer.passHostHeader=true
        - traefik.http.routers.zep.service=zep
    
networks:
  {{network_name}}:
    external: true
    name: {{network_name}}
