name: Build Stacks and Categories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Directory Structure
        run: ls -R

      - name: Make Scripts Executable
        run: chmod +x ./utils/build_stacks_object.sh ./utils/build_categories_array.sh

      - name: Run Scripts
        run: ./utils/build_stacks_object.sh && ./utils/build_categories_array.sh
